
# 🔗 Merge Club Features into Player Dataset (Using Local Paths)

This notebook merges your three main datasets:

- `clubs_dataset.csv`: Base dataset with club names and core metadata
- `african_clubs_features_dataset.csv`: Club-level enrichment (tier, exposure, etc.)
- `players_dataset.csv`: Player dataset to be enriched with club + league features

We will:
1. Load and inspect all files
2. Merge club features into clubs dataset
3. Merge enriched clubs into player dataset
4. Export a new `players_dataset_enriched.csv` file

## 📥 Step 1: Load All Datasets

In [1]:
import pandas as pd

# Load datasets using your full paths
clubs_df = pd.read_csv(r"C:/Users/nadza/OneDrive/Desktop/Tactic_Sense_Dataset/clubs_dataset.csv")
features_df = pd.read_csv(r"C:/Users/nadza/OneDrive/Desktop/Tactic_Sense_Dataset/african_clubs_features_dataset.csv")
players_df = pd.read_csv(r"C:/Users/nadza/OneDrive/Desktop/Tactic_Sense_Dataset/players_dataset.csv")

# Preview clubs dataset
clubs_df.head()

,ranking,club name,country,league,stadium,formation_preference,playing_style,market_budget,salary_budget,transfer_history,avg_transfer_fee_paid,avg_contract_length,verified_status,recruitment_priority,scouting_focus,profile_rating,sponsorship_deals,social_media_links
0,265,1o de Agosto,Angola,Girabola,Estadio 11 de Novembro,'3-4-2-1',North African Technical,3.634855e+09,1.453942e+09,"{""last_5_transfers"": [{""year"": 2021, ""player"":...",523560.538980,3 years,True,Academy graduates,Asian market,5.87,"{""kit_sponsor"": ""Adidas"", ""main_sponsor"": ""Soc...","{""facebook"": ""facebook.com/club_5989"", ""twitte..."
1,2530,1o de Maio,Angola,Segunda Divisao,Estadio 11 de Novembro,'4-5-1',High Press,9.540010e+08,3.816004e+08,"{""last_5_transfers"": [{""year"": 2020, ""player"":...",269316.382051,2 years,True,Young prospects,African talents,7.82,"{""kit_sponsor"": ""Umbro"", ""main_sponsor"": ""Al B...","{""facebook"": ""facebook.com/club_8015"", ""twitte..."
2,945,Abia Warriors,Nigeria,Nigeria Professional Football League,Moshood Abiola National Stadium,'3-6-1',Tiki-Taka Adaptation,1.161430e+09,4.645720e+08,"{""last_5_transfers"": [{""year"": 2019, ""player"":...",184675.718713,2 years,False,International players,Local academy,7.39,"{""kit_sponsor"": ""Macron"", ""main_sponsor"": ""Tun...","{""facebook"": ""facebook.com/club_2626"", ""twitte..."
3,2267,AC Mamahira,Mali,Malian Premiere Division,Stade 26 Mars,'3-5-1-1',Defensive Structure,4.126500e+08,1.650600e+08,"{""last_5_transfers"": [{""year"": 2024, ""player"":...",307666.374121,4 years,False,Local talent,European market,0.47,"{""kit_sponsor"": ""Hummel"", ""main_sponsor"": ""Vit...","{""facebook"": ""facebook.com/club_5262"", ""twitte..."
4,1128,Academia F. Amadou Diallo,Ivory Coast,Ligue 2,Stade Olympique Alassane Ouattara,'3-3-3-1',Tiki-Taka Adaptation,2.912799e+09,1.165120e+09,"{""last_5_transfers"": [{""year"": 2020, ""player"":...",699152.821871,2 years,False,Proven professionals,Local academy,8.85,"{""kit_sponsor"": ""Kappa"", ""main_sponsor"": ""Sams...","{""facebook"": ""facebook.com/club_4578"", ""twitte..."

# Merge club-level features into base club data
clubs_enriched = clubs_df.merge(features_df, how="left", on="club name")

# Preview result
clubs_enriched.head()

In [3]:
print(clubs_df.columns.tolist())
print(features_df.columns.tolist())

['ranking', 'club name', 'country', 'league', 'stadium', 'formation_preference', 'playing_style', 'market_budget', 'salary_budget', 'transfer_history', 'avg_transfer_fee_paid', 'avg_contract_length', 'verified_status', 'recruitment_priority', 'scouting_focus', 'profile_rating', 'sponsorship_deals', 'social_media_links']
['club_name', 'club_tier', 'international_exposure', 'league_strength', 'league_exposure', 'club_reputation_notes']

In [4]:
# Merge club-level features into clubs
clubs_enriched = clubs_df.merge(features_df, how="left", left_on="club name", right_on="club_name")

# Preview result
clubs_enriched.head()

,ranking,club name,country,league,stadium,formation_preference,playing_style,market_budget,salary_budget,transfer_history,...,scouting_focus,profile_rating,sponsorship_deals,social_media_links,club_name,club_tier,international_exposure,league_strength,league_exposure,club_reputation_notes
0,265,1o de Agosto,Angola,Girabola,Estadio 11 de Novembro,'3-4-2-1',North African Technical,3.634855e+09,1.453942e+09,"{""last_5_transfers"": [{""year"": 2021, ""player"":...",...,Asian market,5.87,"{""kit_sponsor"": ""Adidas"", ""main_sponsor"": ""Soc...","{""facebook"": ""facebook.com/club_5989"", ""twitte...",NaN,NaN,NaN,NaN,NaN,NaN
1,2530,1o de Maio,Angola,Segunda Divisao,Estadio 11 de Novembro,'4-5-1',High Press,9.540010e+08,3.816004e+08,"{""last_5_transfers"": [{""year"": 2020, ""player"":...",...,African talents,7.82,"{""kit_sponsor"": ""Umbro"", ""main_sponsor"": ""Al B...","{""facebook"": ""facebook.com/club_8015"", ""twitte...",NaN,NaN,NaN,NaN,NaN,NaN
2,945,Abia Warriors,Nigeria,Nigeria Professional Football League,Moshood Abiola National Stadium,'3-6-1',Tiki-Taka Adaptation,1.161430e+09,4.645720e+08,"{""last_5_transfers"": [{""year"": 2019, ""player"":...",...,Local academy,7.39,"{""kit_sponsor"": ""Macron"", ""main_sponsor"": ""Tun...","{""facebook"": ""facebook.com/club_2626"", ""twitte...",Abia Warriors,Tier 1,Low,3.0,Medium,"Competes in Nigerian Premier League, not inter..."
3,2267,AC Mamahira,Mali,Malian Premiere Division,Stade 26 Mars,'3-5-1-1',Defensive Structure,4.126500e+08,1.650600e+08,"{""last_5_transfers"": [{""year"": 2024, ""player"":...",...,European market,0.47,"{""kit_sponsor"": ""Hummel"", ""main_sponsor"": ""Vit...","{""facebook"": ""facebook.com/club_5262"", ""twitte...",AC Mamahira,Tier 2,NaN,1.5,Low,Limited data; likely local Malian club
4,1128,Academia F. Amadou Diallo,Ivory Coast,Ligue 2,Stade Olympique Alassane Ouattara,'3-3-3-1',Tiki-Taka Adaptation,2.912799e+09,1.165120e+09,"{""last_5_transfers"": [{""year"": 2020, ""player"":...",...,Local academy,8.85,"{""kit_sponsor"": ""Kappa"", ""main_sponsor"": ""Sams...","{""facebook"": ""facebook.com/club_4578"", ""twitte...",Academia F. Amadou Diallo,Tier 2,Low (Academy ties),2.0,Medium,Youth-focused club in Côte d'Ivoire; exports p...

## 👥 Step 3: Merge Clubs into Players Dataset

In [6]:
print(players_df.columns.tolist())

['player_id', 'full_name', 'email', 'date_of_birth', 'age', 'nationality', 'position', 'secondary_position', 'club', 'league', 'market_value_eur', 'salary_expectation', 'contract_status', 'fitness_level', 'medical_history', 'last_5_match_performance', 'skills_rating', 'weaknesses', 'goals', 'assists', 'preferred_foot', 'verified_status', 'likes_from_pros', 'scouting_score', 'tactic_fit_score', 'career_path_suggestions', 'training_recommendations', 'profile_rating', 'created_at', 'yellow_cards', 'red_cards', 'matches_suspended', 'last_incident_date', 'goal_contributions', 'discipline_score', 'value_category', 'age_group', 'skill_handling', 'skill_reflexes', 'skill_positioning', 'skill_finishing', 'skill_dribbling', 'skill_speed', 'skill_passing', 'skill_vision', 'skill_tackling', 'skill_marking', 'skill_heading', 'value_salary_ratio']

In [7]:
# Merge enriched club features into player dataset
players_enriched = players_df.merge(
    clubs_enriched, 
    how="left", 
    left_on="club", 
    right_on="club name"
)

# Fill missing values safely
players_enriched["league_strength"] = players_enriched["league_strength"].fillna(1)
players_enriched["club_tier"] = players_enriched["club_tier"].fillna(1)
players_enriched["league_exposure"] = players_enriched["league_exposure"].fillna("Low")
players_enriched["international_exposure"] = players_enriched["international_exposure"].fillna("No")

# Preview
players_enriched.head()

,player_id,full_name,email,date_of_birth,age,nationality,position,secondary_position,club,league_x,...,scouting_focus,profile_rating_y,sponsorship_deals,social_media_links,club_name,club_tier,international_exposure,league_strength,league_exposure,club_reputation_notes
0,1,Mamadou Diop,mamadou.diop@football.com,2003-01-01,22,senegal,goalkeeper,NaN,Linguère,Nigeria Professional Football League,...,NaN,NaN,NaN,NaN,NaN,1,No,1.0,Low,NaN
1,2,Lamin Saidy,lamin.saidy@football.com,2003-03-29,21,gambia,goalkeeper,NaN,Waa Banjul,Nigeria Professional Football League,...,NaN,NaN,NaN,NaN,NaN,1,No,1.0,Low,NaN
2,3,Issaka Oumarou,issaka.oumarou@football.com,2003-05-13,21,niger,goalkeeper,NaN,Gendarmerie Nationale,Nigeria Professional Football League,...,NaN,NaN,NaN,NaN,NaN,1,No,1.0,Low,NaN
3,4,Joao Simbine,joao.simbine@football.com,2003-06-09,21,mozambique,goalkeeper,NaN,Ferroviário de Nampula,Nigeria Professional Football League,...,NaN,NaN,NaN,NaN,NaN,1,No,1.0,Low,NaN
4,5,Diogo Silva,diogo.silva@football.com,2003-06-16,21,portugal,goalkeeper,NaN,Vizela,Nigeria Professional Football League,...,NaN,NaN,NaN,NaN,NaN,1,No,1.0,Low,NaN

## 💾 Step 4: Export Final Enriched Player Dataset

In [8]:
# Export the final enriched player dataset to your folder
players_enriched.to_csv(r"C:/Users/nadza/OneDrive/Desktop/Tactic_Sense_Dataset/players_dataset_enriched.csv", index=False)

print("✅ Exported successfully to: C:/Users/nadza/OneDrive/Desktop/Tactic_Sense_Dataset/players_dataset_enriched.csv")

✅ Exported successfully to: C:/Users/nadza/OneDrive/Desktop/Tactic_Sense_Dataset/players_dataset_enriched.csv